/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SaleItem = IDL.Record({
  'size' : IDL.Text,
  'productId' : IDL.Text,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
});
export const ProductId = IDL.Nat;
export const Category = IDL.Variant({
  'Sarees' : IDL.Null,
  'CoordSets' : IDL.Null,
  'Kurties' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : Category,
  'price' : IDL.Nat,
});
export const SaleId = IDL.Nat;
export const Sale = IDL.Record({
  'id' : SaleId,
  'customerName' : IDL.Text,
  'total' : IDL.Nat,
  'date' : Timestamp,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
  'items' : IDL.Vec(SaleItem),
});
export const VisitRecord = IDL.Record({
  'page' : IDL.Text,
  'timestamp' : Timestamp,
});
export const CostPriceEntry = IDL.Record({
  'productId' : IDL.Text,
  'costPrice' : IDL.Float64,
});
export const DynamicCategory = IDL.Record({
  'id' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'name' : IDL.Text,
});
export const DynamicProduct = IDL.Record({
  'id' : IDL.Text,
  'categoryId' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'sizes' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Opt(IDL.Text),
  'price' : IDL.Nat,
});
export const ProductOverride = IDL.Record({
  'description' : IDL.Opt(IDL.Text),
  'productId' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'price' : IDL.Opt(IDL.Nat),
});
export const StockEntry = IDL.Record({
  'size' : IDL.Text,
  'productId' : IDL.Text,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addDynamicCategory' : IDL.Func([IDL.Text], [IDL.Text], []),
  'addDynamicProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Text],
      [],
    ),
  'addSale' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(SaleItem), IDL.Nat],
      [],
      [],
    ),
  'deductStock' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'deleteDynamicCategory' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteDynamicProduct' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'getAnalytics' : IDL.Func([], [IDL.Vec(VisitRecord)], ['query']),
  'getCostPrices' : IDL.Func([], [IDL.Vec(CostPriceEntry)], ['query']),
  'getDynamicCategories' : IDL.Func([], [IDL.Vec(DynamicCategory)], ['query']),
  'getDynamicProducts' : IDL.Func([], [IDL.Vec(DynamicProduct)], ['query']),
  'getDynamicProductsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DynamicProduct)],
      ['query'],
    ),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductById' : IDL.Func([ProductId], [Product], ['query']),
  'getProductOverrides' : IDL.Func([], [IDL.Vec(ProductOverride)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getStock' : IDL.Func([], [IDL.Vec(StockEntry)], ['query']),
  'init' : IDL.Func([], [], []),
  'initStock' : IDL.Func([IDL.Vec(StockEntry)], [], []),
  'recordVisit' : IDL.Func([IDL.Text], [], []),
  'resetAllStock' : IDL.Func([], [], []),
  'setCategoryOrder' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'setCostPrice' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'setDynamicProductOrder' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'setProductOverride' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'setStockEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateDynamicCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateDynamicProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Bool,
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SaleItem = IDL.Record({
    'size' : IDL.Text,
    'productId' : IDL.Text,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Timestamp = IDL.Int;
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const ProductId = IDL.Nat;
  const Category = IDL.Variant({
    'Sarees' : IDL.Null,
    'CoordSets' : IDL.Null,
    'Kurties' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : Category,
    'price' : IDL.Nat,
  });
  const SaleId = IDL.Nat;
  const Sale = IDL.Record({
    'id' : SaleId,
    'customerName' : IDL.Text,
    'total' : IDL.Nat,
    'date' : Timestamp,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
    'items' : IDL.Vec(SaleItem),
  });
  const VisitRecord = IDL.Record({
    'page' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const CostPriceEntry = IDL.Record({
    'productId' : IDL.Text,
    'costPrice' : IDL.Float64,
  });
  const DynamicCategory = IDL.Record({
    'id' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'name' : IDL.Text,
  });
  const DynamicProduct = IDL.Record({
    'id' : IDL.Text,
    'categoryId' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'sizes' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Opt(IDL.Text),
    'price' : IDL.Nat,
  });
  const ProductOverride = IDL.Record({
    'description' : IDL.Opt(IDL.Text),
    'productId' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'price' : IDL.Opt(IDL.Nat),
  });
  const StockEntry = IDL.Record({
    'size' : IDL.Text,
    'productId' : IDL.Text,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addDynamicCategory' : IDL.Func([IDL.Text], [IDL.Text], []),
    'addDynamicProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Text],
        [],
      ),
    'addSale' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(SaleItem), IDL.Nat],
        [],
        [],
      ),
    'deductStock' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'deleteDynamicCategory' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteDynamicProduct' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'getAnalytics' : IDL.Func([], [IDL.Vec(VisitRecord)], ['query']),
    'getCostPrices' : IDL.Func([], [IDL.Vec(CostPriceEntry)], ['query']),
    'getDynamicCategories' : IDL.Func(
        [],
        [IDL.Vec(DynamicCategory)],
        ['query'],
      ),
    'getDynamicProducts' : IDL.Func([], [IDL.Vec(DynamicProduct)], ['query']),
    'getDynamicProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DynamicProduct)],
        ['query'],
      ),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductById' : IDL.Func([ProductId], [Product], ['query']),
    'getProductOverrides' : IDL.Func([], [IDL.Vec(ProductOverride)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getStock' : IDL.Func([], [IDL.Vec(StockEntry)], ['query']),
    'init' : IDL.Func([], [], []),
    'initStock' : IDL.Func([IDL.Vec(StockEntry)], [], []),
    'recordVisit' : IDL.Func([IDL.Text], [], []),
    'resetAllStock' : IDL.Func([], [], []),
    'setCategoryOrder' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'setCostPrice' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'setDynamicProductOrder' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'setProductOverride' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'setStockEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateDynamicCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateDynamicProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Bool,
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };