/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'Sarees' : null } |
  { 'CoordSets' : null } |
  { 'Kurties' : null };
export interface ContactMessage {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Timestamp,
}
export interface CostPriceEntry { 'productId' : string, 'costPrice' : number }
export interface Product {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'isFeatured' : boolean,
  'category' : Category,
  'price' : bigint,
}
export type ProductId = bigint;
export interface Sale {
  'id' : SaleId,
  'customerName' : string,
  'total' : bigint,
  'date' : Timestamp,
  'address' : string,
  'mobile' : string,
  'items' : Array<SaleItem>,
}
export type SaleId = bigint;
export interface SaleItem {
  'size' : string,
  'productId' : string,
  'productName' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface StockEntry {
  'size' : string,
  'productId' : string,
  'productName' : string,
  'quantity' : bigint,
  'category' : string,
}
export type Timestamp = bigint;
export interface VisitRecord { 'page' : string, 'timestamp' : Timestamp }
export interface _SERVICE {
  'addSale' : ActorMethod<
    [string, string, string, Array<SaleItem>, bigint],
    undefined
  >,
  'deductStock' : ActorMethod<[string, string, bigint], undefined>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllSales' : ActorMethod<[], Array<Sale>>,
  'getAnalytics' : ActorMethod<[], Array<VisitRecord>>,
  'getCostPrices' : ActorMethod<[], Array<CostPriceEntry>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getProductById' : ActorMethod<[ProductId], Product>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getStock' : ActorMethod<[], Array<StockEntry>>,
  'init' : ActorMethod<[], undefined>,
  'initStock' : ActorMethod<[Array<StockEntry>], undefined>,
  'recordVisit' : ActorMethod<[string], undefined>,
  'resetAllStock' : ActorMethod<[], undefined>,
  'setCostPrice' : ActorMethod<[string, number], undefined>,
  'setStockEntry' : ActorMethod<
    [string, string, string, string, bigint],
    undefined
  >,
  'submitContactMessage' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];